### ISSUE TITLE
Possible merge?

### ISSUE THREAD

**Issue by Specimen-420** [OneGunBullet/Bare-Metals#3]
Hey, I'll make this quick but i was wondering if you'd like to merge projects? specifically with this project: https://modrinth.com/resourcepack/bare-bones-modded-compat

Ive made packs like this one here: https://www.curseforge.com/minecraft/texture-packs/bare-bones-x-fresh-animations

Message me on discord @Specimen_420 if you are interested and want further details or to negotiate.

Thanks.

**Comment by OneGunBullet** [comment]
Hi! I recognize you from the Bare Bones discord server lol. I've been visiting family last 2 weeks so sorry for the late response. 

I think we should keep our projects separate. The Create mod itself has a lot of add-ons so I think it'll be more clearer to have the Create mod it's own resource pack, some people might not like the larger download size. If you would like, we could add links to each others projects instead?
